version: "3.0"
services:
  poll:
    build: poll
    ports:
      - "5000:80"
    networks:
      - poll-tier
    environment:
      - POLL_HOSTNAME=poll
      - REDIS_IP=redis
      - OPTION_A=LoL
      - OPTION_B=Genshin Impact
      - OPTION_C=Overwash
      - OPTION_D=Clone Hero
    restart: on-failure
  redis:
    image: redis
    expose:
      - "6379"
    networks:
      - poll-tier
      - back-tier
    restart: on-failure
  worker:
    depends_on:
      - db
      - redis
    build: worker
    networks:
      - back-tier
    environment:
      - WORKER_HOSTNAME=worker
    restart: on-failure
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - result-tier
      - back-tier
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432"
    restart: on-failure
  result:
    depends_on:
      - db
    build: result
    ports:
      - "5001:80"
    networks:
      - result-tier
    environment:
      - RESULT_HOSTNAME=result
    restart: on-failure
networks:
  poll-tier:
  result-tier:
  back-tier:
volumes:
  db-data:
